### ISSUE TITLE
Boolean property use property name or omit

### ISSUE THREAD

**Issue by patrickplaggenborg** [naftalibeder/figma-frame-exporter#2]
With multiple boolean properties, filenames become difficult to interpret: 'layer no no yes yes'.

This (old) plugin has a good implementation of boolean variants:
https://www.figma.com/community/plugin/996640798188777330/Export-Variants

Would it be possible to implement something similar?

Variant with 'true' or 'on' value:
    - Property name will be used instead of the value 

Variant with 'off' or 'false' value:
    - Property is omitted

**Comment by naftalibeder** [comment]
~Closed in favor of #4.~

**Comment by naftalibeder** [comment]
@patrickplaggenborg Thanks for opening this issue! This is now implemented in the published plugin.
