### ISSUE TITLE
Omit Before and After setting

### ISSUE THREAD

**Issue by patrickplaggenborg** [naftalibeder/figma-frame-exporter#3]
At first I thought they were used to insert characters before/after each variant. But it looks like they are used to insert characters before/after the entire set of variants.

I might be missing an advanced use case, but can the **Before** and **After** fields not simply be removed?

In the current filename format field (`$F $V`) you can already add characters before and after the variant names.

All you then need is the 'Between' field to specify what character to use between each variant.

**Comment by naftalibeder** [comment]
@patrickplaggenborg There was a reason, but not a great one - if you had some frames with variants and some without, a `Before` connector would appear for the one with the variants, but not for the one without.

But I don't think that's a common use case, so I removed those fields.
