### ISSUE TITLE
Export [x] images label is incorrect

### ISSUE THREAD

**Issue by germain-gg** [naftalibeder/figma-frame-exporter#6]
Thank you for the Figma Frame Exporter plugin, it works really well and helped me out quite a lot!

# Steps to reproduce

1. Select more than 20 frames
2. See the preview icons capped at 20 items

# Expected output

for the previews to be capped at 20, but for the bottom links to say "Export [x] images" where x is the actual number of frames selected.

# Actual output

The label says "Export 20 images" even though there are more than 20 images in the final zip that gets downloaded.

From a very quick glance is seems that this numbers comes from the `limit` default value on the `_refreshPreview` function signature.

**Comment by naftalibeder** [comment]
Thanks for the clear report! Should be a pretty simple fix. I’ll look into it shortly.

**Comment by naftalibeder** [comment]
Fixed in https://github.com/naftalibeder/figma-frame-exporter/commit/6e21c7c6037966e3dce9423e26bef0075e1bec86.
