### ISSUE TITLE
Improvement to the plugin

### ISSUE THREAD

**Issue by kitsune-jt** [naftalibeder/figma-frame-exporter#9]
First of all, thank you for contributing your Frame Explorer plugin to the Figma community. I have a feature request for your plugin. If you could possibly add a regex filter regex.match(file_name) to it that would allow to add only those files which witch match certain pattern in the name to only be able to download those assets, that would be great. Also, any chance that the file formats in which we can export the assets would be on a multiselct rather than mutually exclusive?

**Comment by naftalibeder** [comment]
Both are good ideas, thank you. Closing this in favor of #10 and #11.
